# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "뉴스젤리 콘텐츠팀 블로그"
description: > # this means to ignore newlines until "email:"
   뉴스젤리 콘텐츠팀 블로그입니다.

email: help@newsjel.ly
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: '뉴스젤리'
author: '뉴스젤리'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://newsjelly.github.io/blog-contents/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@newsjelly'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

 - icon:	facebook
   url:	https://www.facebook.com/newsjelly
   desc: Connect with me facebook
   share_url: https://www.facebook.com/sharer.php
   share_title: ?t=
   share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
